drop table if exists Reviews;
CREATE TABLE Reviews (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(50) NOT NULL,
score INT(5) UNSIGNED NOT NULL,
item VARCHAR(50) NOT NULL,
review VARCHAR(500) NOT NULL,
post_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
INSERT INTO Reviews (email, score,item,review) VALUES ('Detra@example.com',1,'alw_51m','Terrible!!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Detra@example.com',5,'alw_arr','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Detra@example.com',4,'alw_m15','not Bad');
INSERT INTO Reviews (email, score,item,review) VALUES ('Detra@example.com',1,'alw_m17','Terrible!!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Detra@example.com',2,'alw_r8','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Detra@example.com',1,'alw_ryzen','Terrible!!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Detra@example.com',3,'apl_imac','Just so so');
INSERT INTO Reviews (email, score,item,review) VALUES ('Detra@example.com',2,'apl_imp','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Detra@example.com',1,'apl_mba','Terrible!!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Detra@example.com',4,'apl_mbp','not Bad');
INSERT INTO Reviews (email, score,item,review) VALUES ('Corene@example.com',1,'alw_51m','Terrible!!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Corene@example.com',2,'alw_arr','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Corene@example.com',5,'alw_m15','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Corene@example.com',2,'alw_m17','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Corene@example.com',5,'alw_r8','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Corene@example.com',4,'alw_ryzen','not Bad');
INSERT INTO Reviews (email, score,item,review) VALUES ('Corene@example.com',3,'apl_imac','Just so so');
INSERT INTO Reviews (email, score,item,review) VALUES ('Corene@example.com',3,'apl_imp','Just so so');
INSERT INTO Reviews (email, score,item,review) VALUES ('Corene@example.com',5,'apl_mba','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Corene@example.com',3,'apl_mbp','Just so so');
INSERT INTO Reviews (email, score,item,review) VALUES ('Kurtis@example.com',5,'alw_51m','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Kurtis@example.com',1,'alw_arr','Terrible!!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Kurtis@example.com',4,'alw_m15','not Bad');
INSERT INTO Reviews (email, score,item,review) VALUES ('Kurtis@example.com',2,'alw_m17','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Kurtis@example.com',5,'alw_r8','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Kurtis@example.com',2,'alw_ryzen','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Kurtis@example.com',2,'apl_imac','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Kurtis@example.com',1,'apl_imp','Terrible!!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Kurtis@example.com',1,'apl_mba','Terrible!!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Kurtis@example.com',2,'apl_mbp','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Shila@example.com',5,'alw_51m','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Shila@example.com',2,'alw_arr','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Shila@example.com',3,'alw_m15','Just so so');
INSERT INTO Reviews (email, score,item,review) VALUES ('Shila@example.com',2,'alw_m17','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Shila@example.com',2,'alw_r8','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Shila@example.com',4,'alw_ryzen','not Bad');
INSERT INTO Reviews (email, score,item,review) VALUES ('Shila@example.com',5,'apl_imac','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Shila@example.com',5,'apl_imp','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Shila@example.com',1,'apl_mba','Terrible!!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Shila@example.com',1,'apl_mbp','Terrible!!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Jovita@example.com',4,'alw_51m','not Bad');
INSERT INTO Reviews (email, score,item,review) VALUES ('Jovita@example.com',5,'alw_arr','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Jovita@example.com',1,'alw_m15','Terrible!!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Jovita@example.com',4,'alw_m17','not Bad');
INSERT INTO Reviews (email, score,item,review) VALUES ('Jovita@example.com',5,'alw_r8','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Jovita@example.com',5,'alw_ryzen','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Jovita@example.com',1,'apl_imac','Terrible!!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Jovita@example.com',5,'apl_imp','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Jovita@example.com',4,'apl_mba','not Bad');
INSERT INTO Reviews (email, score,item,review) VALUES ('Jovita@example.com',3,'apl_mbp','Just so so');
INSERT INTO Reviews (email, score,item,review) VALUES ('Akiko@example.com',2,'alw_51m','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Akiko@example.com',5,'alw_arr','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Akiko@example.com',3,'alw_m15','Just so so');
INSERT INTO Reviews (email, score,item,review) VALUES ('Akiko@example.com',5,'alw_m17','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Akiko@example.com',3,'alw_r8','Just so so');
INSERT INTO Reviews (email, score,item,review) VALUES ('Akiko@example.com',5,'alw_ryzen','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Akiko@example.com',1,'apl_imac','Terrible!!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Akiko@example.com',2,'apl_imp','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Akiko@example.com',2,'apl_mba','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Akiko@example.com',4,'apl_mbp','not Bad');
INSERT INTO Reviews (email, score,item,review) VALUES ('Juli@example.com',3,'alw_51m','Just so so');
INSERT INTO Reviews (email, score,item,review) VALUES ('Juli@example.com',4,'alw_arr','not Bad');
INSERT INTO Reviews (email, score,item,review) VALUES ('Juli@example.com',2,'alw_m15','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Juli@example.com',2,'alw_m17','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Juli@example.com',5,'alw_r8','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Juli@example.com',1,'alw_ryzen','Terrible!!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Juli@example.com',3,'apl_imac','Just so so');
INSERT INTO Reviews (email, score,item,review) VALUES ('Juli@example.com',1,'apl_imp','Terrible!!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Juli@example.com',5,'apl_mba','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Juli@example.com',2,'apl_mbp','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Dillon@example.com',3,'alw_51m','Just so so');
INSERT INTO Reviews (email, score,item,review) VALUES ('Dillon@example.com',3,'alw_arr','Just so so');
INSERT INTO Reviews (email, score,item,review) VALUES ('Dillon@example.com',4,'alw_m15','not Bad');
INSERT INTO Reviews (email, score,item,review) VALUES ('Dillon@example.com',2,'alw_m17','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Dillon@example.com',5,'alw_r8','I like this!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Dillon@example.com',2,'alw_ryzen','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Dillon@example.com',2,'apl_imac','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Dillon@example.com',1,'apl_imp','Terrible!!!!');
INSERT INTO Reviews (email, score,item,review) VALUES ('Dillon@example.com',2,'apl_mba','Wasting my money');
INSERT INTO Reviews (email, score,item,review) VALUES ('Dillon@example.com',1,'apl_mbp','Terrible!!!!');